// --- data lists ---
const class_list = ['Bard', 'Barbarian', 'Wizard', 'Rogue', 'Cleric', 'Paladin', 'Fighter', 'Ranger', 'Druid', 'Monk', 'Sorcerer'];
const eyecolor_list = ['Blue', 'Gray', 'Brown', 'Black', 'Green', 'Yellow', 'Red', 'Orange', 'White', 'Purple'];
const haircolor_list = ['Blue', 'Gray', 'Brown', 'Black', 'Green', 'Yellow', 'Red', 'Orange', 'White', 'Purple'];
const level_list = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'];
const mood_list = ['angry', 'sad', 'happy', 'afraid', 'surprised', 'disgusted', 'contemptuous', 'love', 'lustful', 'shy', 'rage', 'trustful', 'anticipatory', 'indifferent', 'amused', 'anxious', 'awe', 'interested', 'envious', 'blah'];
const personality_list = ['loyal and sensible', 'responsible and caring', 'humanitarian and pragmatic', 'logical and systematic', 'independent and spontaneous', 'introspective and creative', 'quiet and sensitive', 'curious and intellectual', 'a free spirit', 'an entertainer', 'innovative and endlessly positive', 'an out of the box thinker and quiet', 'hard working and pragmatic', 'personable and go-getting', 'helpful and engaging', 'a born leader', 'angry and spiteful', 'hateful and jealous', 'wrathful and vengeful', 'psychotic and unstable'];
const gender_list = ['Male', 'Female', 'Nonbinary'];
const race_list = {
  'human': {
    Notes: '+1 feat at 1st level, 4 bonus skill points at 1st level, +1 per level thereafter, Favored Class: Any'
  },
  'dwarf': {
    Str: '+2',
    Cha: '-2',
    Notes: 'Darkvision 60 ft. Stonecunning, weapon familiarity (dwarven weapons), stability, +2 vs poison, spells, and spell-like effects. Favored Class: Fighter'
  },
  'elf': {
    Dex: '+2',
    Con: '-2',
    Notes: 'Low-light vision, Proficient with longsword, rapier, longbow, and shortbow, Immune to magic sleep; +2 vs enchantments, +2 Listen, Search, Spot. Favored Class: Wizard'
  },
  'gnome': {
    Str: '-2',
    Con: '+2',
    Notes: 'Small size, Low-light vision, +2 saving throws vs illusions, Speak with animals (burrowing mammals), +1 to DCs of illusion spells. Favored Class: Bard'
  },
  'half-elf': {
    Notes: '+1 Listen, Search, Spot, Immune to sleep spells, +2 Diplomacy, Gather Information, Low-light vision. Favored Class: Any'
  },
  'half-orc': {
    Str: '+2',
    Int: '-2',
    Cha: '-2',
    Notes: 'Darkvision 60 ft. Favored Class: Barbarian'
  },
  'halfling': {
    Str: '-2',
    Dex: '+2',
    Notes: 'Small size, +1 all saving throws, +2 Climb, Jump, Move Silently. Favored Class: Rogue'
  },
  'goblin': {
    Str: '-2',
    Dex: '+2',
    Cha: '-2',
    Notes: 'Small humanoid, +4 Move Silently, Darkvision 60 ft. +1 racial bonus on Ride and Move Silently'
  },
  'orc': {
    Str: '+4',
    Int: '-2',
    Wis: '-2',
    Cha: '-2',
    Notes: 'Darkvision 60 ft. Light sensitivity'
  },
  'kobold': {
    Str: '-4',
    Dex: '+2',
    Con: '-2',
    Notes: 'Darkvision 60 ft. +1 Craft (trapmaking), Profession (miner), Search (stonework)'
  },
  'gnoll': {
    Str: '+2',
    Int: '-2',
    Notes: 'Darkvision 60 ft.'
  },
  'lizardfolk': {
    Str: '+2',
    Con: '+2',
    Int: '-2',
    Notes: 'Natural armor +5, swim speed 15 ft.'
  },
  'merfolk': {
    Str: '-2',
    Dex: '+2',
    Notes: 'Swim speed 50 ft., low-light vision, Amphibious (can breathe air and water)'
  },
  'troglodyte': {
    Str: '+4',
    Dex: '-2',
    Con: '+4',
    Int: '-2',
    Cha: '-2',
    Notes: 'Darkvision 90 ft., stench aura, Natural armor +6'
  },
  'aasimar': {
    Wis: '+2',
    Cha: '+2',
    Notes: 'Darkvision 60 ft., daylight 1/day, Resistance to acid, cold, electricity 5. Favored Class: Paladin Level Adjust +1'
  },
  'tiefling': {
    Dex: '+2',
    Int: '+2',
    Cha: '-2',
    Notes: 'Darkvision 60 ft., darkness 1/day, Resistance to cold, fire, electricity 5. Favored Class: Rogue, Level Adjustment +1'
  },
  'drow': {
    Dex: '+2',
    Con: '-2',
    Int: '+2',
    Cha: '+2',
    Notes: 'Darkvision 120 ft., spell resistance, light blindness, Spell-like abilities: dancing lights, darkness, faerie fire, Proficient with rapiers, longswords, hand crossbows, Level Adjustment +2'
  },
  'githyanki': {
    Dex: '+2',
    Wis: '-2',
    Notes: 'Darkvision 60 ft. Natural armor +1, Psi-like abilities: daunt, dimension door, psionic teleport (levels vary), Level Adjustment +2'
  },
  'azer': {
    Str: '+2',
    Dex: '+2',
    Con: '+2',
    Int: '+2',
    Wis: '+2',
    Cha: '-2',
    Notes: 'Darkvision 60 ft. Natural armor +6, Special attack (Heat), Immune to fire, SR 13 + class level, Vulnerable to Cold, Level Adjustment +4'
  },
  'bugbear': {
    Str: '+4',
    Dex: '+2',
    Con: '+2',
    Cha: '-2',
    Notes: 'Darkvision 60 ft. Natural armor +3, Level Adjustment +1'
  },
  'centaur': {
    Str: '+8',
    Dex: '+4',
    Con: '+4',
    Int: '-2',
    Wis: '+2',
    Notes: 'Large sized, Space/Reach 10ft/5ft, Speed 50 ft. Darkvision 60 ft, Natural armor +3, Level Adjustment +2'
  }
};


// Randomness generator 
function pickRandom(input) {
  if (Array.isArray(input)) {
    return input[Math.floor(Math.random() * input.length)];
  }
  else if (typeof input === 'object') {
    const keys = Object.keys(input);
    const randomKey = keys[Math.floor(Math.random() * keys.length)];
    return { key: randomKey, value: input[randomKey] };
  }
  else {
    throw new Error('pickRandom expects an array or object');
  }
}



// --- main generator ---
function generateOutput() {
  const selectedClass = pickRandom(class_list);
  const eyeColor = pickRandom(eyecolor_list);
  const hairColor = pickRandom(haircolor_list);
  const level = pickRandom(level_list);
  const mood = pickRandom(mood_list);
  const personality = pickRandom(personality_list);
  const gender = pickRandom(gender_list);
  const race = pickRandom(race_list);


  const result = `A ${gender}, ${race.key}, level ${level} ${selectedClass} with ${eyeColor} eyes, ${hairColor} hair, feeling ${mood} while usually ${personality}.\n\n` +
    `Race Stats: ${race.key}\n` +
    JSON.stringify(race.value, null, 2);

  document.getElementById("outputBox").textContent = result;
}
document.getElementById("charGenBox").addEventListener("click", generateOutput);







// for the random adventures

const adventureIdeasList = [
  "Abandon village is haunted by a restless spirit.",
  "Abductions in the city lead to a cult.",
  "Adventurers must retrieve a stolen artifact.",
  "Ancient evil awakens beneath the town.",
  "Assassins target a noble; PCs must protect him.",
  "Bandits threaten trade routes.",
  "Baron has gone mad; stop his tyranny.",
  "Beast terrorizes countryside.",
  "Break a siege laid on a friendly city.",
  "Bridge collapse isolates a region.",
  "Build an outpost in monster-infested territory.",
  "Capture a notorious criminal.",
  "City is overrun by vermin—unnatural cause suspected.",
  "Clerics lose powers; find the reason.",
  "Compete in a grand tournament.",
  "Convince a dragon to aid a kingdom.",
  "Cult attempts to summon a demon.",
  "Curse afflicts a town; discover the source.",
  "Darkness falls permanently on a region.",
  "Defend a caravan from attacks.",
  "Defend town from invading orcs.",
  "Demons run rampant in the wilderness.",
  "Destroy a vampire lord.",
  "Diplomatic mission to hostile territory.",
  "Discover source of poisoned well.",
  "Disgraced noble seeks redemption.",
  "Dragon demands tribute; deal with it.",
  "Escort an important NPC.",
  "Evacuate a village from natural disaster.",
  "Evil artifact must be destroyed.",
  "Expose a traitor in the king’s court.",
  "Face trial for crimes you didn’t commit.",
  "Find a lost explorer.",
  "Find the cure for a strange disease.",
  "Find the heir to a fallen house.",
  "Fire ravages the countryside—arson suspected.",
  "Follow map to legendary treasure.",
  "Forbidden magic causes unnatural effects.",
  "Free slaves from underground mines.",
  "Fugitive hides in monster-infested forest.",
  "Giant sea creature attacks ships.",
  "Goblin uprising threatens region.",
  "Haunted mansion holds family secrets.",
  "Help a ghost find peace.",
  "Hostage situation in a fortress.",
  "Hunt the beast that killed a prince.",
  "Important message must reach city fast.",
  "Investigate mysterious disappearances.",
  "Jewel heist points to insider job.",
  "King cursed by a mysterious figure.",
  "Liberate a temple from evil control.",
  "Lost city found in the jungle.",
  "Magical mishap alters reality.",
  "Marauders raid coastal villages.",
  "Merchant’s goods are cursed.",
  "Messenger never arrived—find out why.",
  "Mine collapses—workers trapped inside.",
  "Missing children linked to fairy ring.",
  "Monster terrorizes local farmlands.",
  "Mysterious island appears off the coast.",
  "Necromancer raises ancient army.",
  "Noble's son joins evil cult.",
  "Old prophecy foretells coming doom.",
  "Oracle sends players on cryptic quest.",
  "Outbreak of lycanthropy in city.",
  "PCs framed for theft of artifact.",
  "Pirates block important shipping lane.",
  "Plague decimates city—find the cause.",
  "Players inherit a haunted castle.",
  "Poisoned crops spark famine.",
  "Political unrest leads to civil war.",
  "Powerful relic causes weather havoc.",
  "Prevent assassination of a ruler.",
  "Protect village during eclipse ritual.",
  "Rare creature is dying out—protect it.",
  "Rebel faction rises in remote area.",
  "Recover a stolen spellbook.",
  "Rescue a kidnapped noble.",
  "Retrieve relic from cursed tomb.",
  "Rival adventurers sabotage your mission.",
  "Sacred spring dries up mysteriously.",
  "Save an ancient tree spirit.",
  "Scrying shows a looming disaster.",
  "Sealed crypt starts leaking undead.",
  "Secrets in dreams must be uncovered.",
  "Seer’s death leads to cursed town.",
  "Shipwreck survivors tell strange tales.",
  "Solve a murder mystery.",
  "Spirits of the past cry for justice.",
  "Stop a rampaging elemental.",
  "Stop volcano from erupting magically.",
  "Storm spirits demand tribute.",
  "Strange portal appears in wilderness.",
  "Strangers arrive bearing dark tidings.",
  "Take over command in losing battle.",
  "Temple vanishes overnight.",
  "Thieves’ guild war spills into streets.",
  "Town celebrates eerie festival.",
  "Train a militia to resist attack.",
  "Travel to other plane to fix problem.",
  "Trolls block crucial mountain pass.",
  "Uncover ancient truth hidden in ruins.",
  "Undead rise during full moon.",
  "Village cursed to forget each day.",
  "Warlord builds fortress—attack imminent.",
  "Warriors return as ghostly avengers.",
  "Weird dreams reveal ancient threat.",
  "Wild magic zone expands dangerously.",
  "Wizard tower erupts with chaos."
];


function generateAdventure() {
  const randomAdventure = pickRandom(adventureIdeasList);
  const randomAdventureResult = `${randomAdventure}`
  document.getElementById("adventure_output_box").textContent = randomAdventureResult;
}
document.getElementById("random_adventures").addEventListener("click", generateAdventure);




// enemies list for generator
//{"name": "", "CR": "", "book": "Monster Manual ", "page": ""},
const monsters = [
  { "name": "Aboleth", "CR": "7", "book": "Monster Manual I", "page": "8" },
  { "name": "Achaierai", "CR": "5", "book": "Monster Manual I", "page": "9" },
  { "name": "Allip", "CR": "3", "book": "Monster Manual I", "page": "10" },
  { "name": "Angel, Astral Deva", "CR": "14", "book": "Monster Manual I", "page": "11" },
  { "name": "Angel, Planetar", "CR": "16", "book": "Monster Manual I", "page": "11" },
  { "name": "Angel, Solar", "CR": "23", "book": "Monster Manual I", "page": "12" },
  { "name": "Animated Object", "CR": "1/2", "book": "Monster Manual I", "page": "13" },
  { "name": "Animated Object", "CR": "1", "book": "Monster Manual I", "page": "13" },
  { "name": "Animated Object", "CR": "2", "book": "Monster Manual I", "page": "13" },
  { "name": "Animated Object", "CR": "3", "book": "Monster Manual I", "page": "14" },
  { "name": "Animated Object", "CR": "5", "book": "Monster Manual I", "page": "14" },
  { "name": "Animated Object", "CR": "7", "book": "Monster Manual I", "page": "14" },
  { "name": "Animated Object", "CR": "10", "book": "Monster Manual I", "page": "14" },
  { "name": "Ankheg", "CR": "3", "book": "Monster Manual I", "page": "14" },
  { "name": "Aranea", "CR": "4", "book": "Monster Manual I", "page": "15" },
  { "name": "Archon, Hound", "CR": "4", "book": "Monster Manual I", "page": "16" },
  { "name": "Archon, Lantern", "CR": "2", "book": "Monster Manual I", "page": "16" },
  { "name": "Archon, Trumpet", "CR": "10", "book": "Monster Manual I", "page": "18" },
  { "name": "Arrowhawk, Juvenile", "CR": "3", "book": "Monster Manual I", "page": "19" },
  { "name": "Arrowhawk, Adult", "CR": "5", "book": "Monster Manual I", "page": "19" },
  { "name": "Arrowhawk, Elder", "CR": "8", "book": "Monster Manual I", "page": "19" },
  { "name": "Assassin Vine", "CR": "3", "book": "Monster Manual I", "page": "20" },
  { "name": "Athach", "CR": "8", "book": "Monster Manual I", "page": "21" },
  { "name": "Azer", "CR": "2", "book": "Monster Manual I", "page": "21" },
  { "name": "Barghest", "CR": "4", "book": "Monster Manual I", "page": "22" },
  { "name": "Barghest, Greater", "CR": "5", "book": "Monster Manual I", "page": "22" },
  { "name": "Basilisk", "CR": "5", "book": "Monster Manual I", "page": "23" },
  { "name": "Basilisk, Greater", "CR": "12", "book": "Monster Manual I", "page": "23" },
  { "name": "Bat, Dire", "CR": "2", "book": "Monster Manual I", "page": "62" },
  { "name": "Bear, Black", "CR": "2", "book": "Monster Manual I", "page": "269" },
  { "name": "Bear, Brown", "CR": "4", "book": "Monster Manual I", "page": "269" },
  { "name": "Bear, Polar", "CR": "4", "book": "Monster Manual I", "page": "269" },
  { "name": "Behir", "CR": "8", "book": "Monster Manual I", "page": "25" },
  { "name": "Beholder", "CR": "13", "book": "Monster Manual I", "page": "25" },
  { "name": "Beholder, Gauth", "CR": "6", "book": "Monster Manual I", "page": "26" },
  { "name": "Belker", "CR": "6", "book": "Monster Manual I", "page": "27" },
  { "name": "Blink Dog", "CR": "2", "book": "Monster Manual ", "page": "28" },
  { "name": "Boar", "CR": "2", "book": "Monster Manual I", "page": "270" },
  { "name": "Bodak", "CR": "8", "book": "Monster Manual I", "page": "28" },
  { "name": "Bugbear", "CR": "2", "book": "Monster Manual I", "page": "29" },
  { "name": "Bulette", "CR": "7", "book": "Monster Manual I", "page": "30" },
  { "name": "Carrion Crawler", "CR": "4", "book": "Monster Manual I", "page": "30" },
  { "name": "Centaur", "CR": "3", "book": "Monster Manual I", "page": "32" },
  { "name": "Chaos Beast", "CR": "7", "book": "Monster Manual I", "page": "33" },
  { "name": "Chimera", "CR": "7", "book": "Monster Manual I", "page": "34" },
  { "name": "Choker", "CR": "2", "book": "Monster Manual I", "page": "34" },
  { "name": "Chuul", "CR": "7", "book": "Monster Manual I", "page": "35" },
  { "name": "Cloaker", "CR": "5", "book": "Monster Manual I", "page": "36" },
  { "name": "Cockatrice", "CR": "3", "book": "Monster Manual I", "page": "37" },
  { "name": "Couatl", "CR": "10", "book": "Monster Manual I", "page": "37" },
  { "name": "Crocodile", "CR": "2", "book": "Monster Manual I", "page": "271" },
  { "name": "Crocodile, Giant", "CR": "4", "book": "Monster Manual I", "page": "271" },
  { "name": "Dark Mantle", "CR": "1", "book": "Monster Manual I", "page": "38" },
  { "name": "Delver", "CR": "9", "book": "Monster Manual I", "page": "39" },
  { "name": "Demon, Babau", "CR": "6", "book": "Monster Manual I", "page": "40" },
  { "name": "Demon, Balor", "CR": "20", "book": "Monster Manual I", "page": "40" },
  { "name": "Demon, Bebilith", "CR": "10", "book": "Monster Manual I", "page": "42" },
  { "name": "Demon, Dretch", "CR": "2", "book": "Monster Manual I", "page": "42" },
  { "name": "Demon, Glabrezu", "CR": "13", "book": "Monster Manual I", "page": "43" },
  { "name": "Demon, Hezrou", "CR": "11", "book": "Monster Manual I", "page": "44" },
  { "name": "Demon, Marilith", "CR": "17", "book": "Monster Manual I", "page": "44" },
  { "name": "Demon, Nalfeshnee", "CR": "14", "book": "Monster Manual I", "page": "45" },
  { "name": "Demon, Quasit", "CR": "2", "book": "Monster Manual I", "page": "46" },
  { "name": "Demon, Retriever", "CR": "11", "book": "Monster Manual I", "page": "46" },
  { "name": "Demon, Succubus", "CR": "7", "book": "Monster Manual I", "page": "47" },
  { "name": "Demon, Vrock", "CR": "9", "book": "Monster Manual I", "page": "48" },
  { "name": "Derro", "CR": "3", "book": "Monster Manual I", "page": "49" },
  { "name": "Destrachan", "CR": "8", "book": "Monster Manual I", "page": "49" },
  { "name": "Devil, Barbed", "CR": "11", "book": "Monster Manual I", "page": "51" },
  { "name": "Devil, Bearded", "CR": "5", "book": "Monster Manual I", "page": "52" },
  { "name": "Devil, Bone", "CR": "9", "book": "Monster Manual I", "page": "52" },
  { "name": "Devil, Chain", "CR": "6", "book": "Monster Manual I", "page": "53" },
  { "name": "Devil, Erinyes", "CR": "8", "book": "Monster Manual I", "page": "54" },
  { "name": "Devil, Hellcat", "CR": "7", "book": "Monster Manual I", "page": "54" },
  { "name": "Devil, Horned", "CR": "16", "book": "Monster Manual I", "page": "55" },
  { "name": "Devil, Ice", "CR": "13", "book": "Monster Manual I", "page": "56" },
  { "name": "Devil, Imp", "CR": "2", "book": "Monster Manual I", "page": "56" },
  { "name": "Devil, Lemure", "CR": "1", "book": "Monster Manual I", "page": "57" },
  { "name": "Devil, Pit Fiend", "CR": "20", "book": "Monster Manual I", "page": "57" },
  { "name": "Devourer", "CR": "11", "book": "Monster Manual I", "page": "58" },
  { "name": "Digester", "CR": "6", "book": "Monster Manual I", "page": "59" },
  { "name": "Dinosaur, Deinonychus", "CR": "3", "book": "Monster Manual I", "page": "60" },
  { "name": "Dinosaur, Elasmosaurus", "CR": "7", "book": "Monster Manual I", "page": "60" },
  { "name": "Dinosaur, Megaraptor", "CR": "6", "book": "Monster Manual I", "page": "60" },
  { "name": "Dinosaur, Triceratops", "CR": "9", "book": "Monster Manual I", "page": "61" },
  { "name": "Dinosaur, Tyrannosaurus", "CR": "8", "book": "Monster Manual I", "page": "61" },
  { "name": "Dire Ape", "CR": "3", "book": "Monster Manual I", "page": "62" },
  { "name": "Dire Badger", "CR": "2", "book": "Monster Manual I", "page": "62" },
  { "name": "Dire Bat", "CR": "2", "book": "Monster Manual I", "page": "62" },
  { "name": "Dire Bear", "CR": "7", "book": "Monster Manual I", "page": "63" },
  { "name": "Dire Boar", "CR": "4", "book": "Monster Manual I", "page": "63" },
  { "name": "Dire Lion", "CR": "5", "book": "Monster Manual I", "page": "63" },
  { "name": "Dire Rat", "CR": "1/3", "book": "Monster Manual I", "page": "64" },
  { "name": "Dire Shark", "CR": "9", "book": "Monster Manual I", "page": "64" },
  { "name": "Dire Tiger", "CR": "8", "book": "Monster Manual I", "page": "65" },
  { "name": "Dire Weasel", "CR": "2", "book": "Monster Manual I", "page": "65" },
  { "name": "Dire Wolf", "CR": "3", "book": "Monster Manual I", "page": "65" },
  { "name": "Dire Wolverine", "CR": "4", "book": "Monster Manual I", "page": "66" },
  { "name": "Displacer Beast", "CR": "4", "book": "Monster Manual I", "page": "66" },
  { "name": "Displacer Beast, Pack Lord", "CR": "12", "book": "Monster Manual I", "page": "66" },
  //-------------------------------I AM HERE -----------------------------------
  { "name": "Djinni", "CR": "5", "book": "Monster Manual I", "page": "65" },
  { "name": "Dog", "CR": "1/3", "book": "Monster Manual I", "page": "66" },
  { "name": "Dog, Riding", "CR": "1", "book": "Monster Manual I", "page": "66" },
  { "name": "Dolphin", "CR": "1/2", "book": "Monster Manual I", "page": "66" },
  { "name": "Dragon Turtle", "CR": "13", "book": "Monster Manual I", "page": "67" },
  { "name": "Dragonne", "CR": "7", "book": "Monster Manual I", "page": "68" },
  { "name": "Drider", "CR": "7", "book": "Monster Manual I", "page": "69" },
  { "name": "Dryad", "CR": "3", "book": "Monster Manual I", "page": "70" },
  { "name": "Dwarf", "CR": "1/2", "book": "Monster Manual I", "page": "70" },
  { "name": "Eagle", "CR": "1/4", "book": "Monster Manual I", "page": "71" },
  { "name": "Eagle, Giant", "CR": "3", "book": "Monster Manual I", "page": "71" },
  { "name": "Efreeti", "CR": "8", "book": "Monster Manual I", "page": "72" },
  { "name": "Elemental, Small", "CR": "1", "book": "Monster Manual I", "page": "73" },
  { "name": "Elemental, Medium", "CR": "3", "book": "Monster Manual I", "page": "73" },
  { "name": "Elemental, Large", "CR": "5", "book": "Monster Manual I", "page": "73" },
  { "name": "Elemental, Huge", "CR": "7", "book": "Monster Manual I", "page": "73" },
  { "name": "Elemental, Greater", "CR": "9", "book": "Monster Manual I", "page": "73" },
  { "name": "Elemental, Elder", "CR": "11", "book": "Monster Manual I", "page": "73" },
  { "name": "Elephant", "CR": "7", "book": "Monster Manual I", "page": "74" },
  { "name": "Elves", "CR": "1/2", "book": "Monster Manual I", "page": "74" },
  { "name": "Ettercap", "CR": "3", "book": "Monster Manual I", "page": "75" },
  { "name": "Ettin", "CR": "6", "book": "Monster Manual I", "page": "76" },
  { "name": "Fire Beetle", "CR": "1/3", "book": "Monster Manual I", "page": "77" },
  { "name": "Formian Worker", "CR": "1/2", "book": "Monster Manual I", "page": "78" },
  { "name": "Formian Warrior", "CR": "2", "book": "Monster Manual I", "page": "78" },
  { "name": "Formian Taskmaster", "CR": "5", "book": "Monster Manual I", "page": "78" },
  { "name": "Formian Myrmarch", "CR": "8", "book": "Monster Manual I", "page": "78" },
  { "name": "Formian Queen", "CR": "12", "book": "Monster Manual I", "page": "78" },
  { "name": "Frost Worm", "CR": "12", "book": "Monster Manual I", "page": "79" },
  { "name": "Fungi, Violet", "CR": "3", "book": "Monster Manual I", "page": "80" },
  { "name": "Gargoyle", "CR": "4", "book": "Monster Manual I", "page": "80" },
  { "name": "Gelatinous Cube", "CR": "3", "book": "Monster Manual I", "page": "81" },
  { "name": "Ghoul", "CR": "1", "book": "Monster Manual I", "page": "81" },
  { "name": "Ghast", "CR": "3", "book": "Monster Manual I", "page": "81" },
  { "name": "Giant, Cloud", "CR": "11", "book": "Monster Manual I", "page": "118" },
  { "name": "Giant, Fire", "CR": "10", "book": "Monster Manual I", "page": "119" },
  { "name": "Giant, Frost", "CR": "9", "book": "Monster Manual I", "page": "120" },
  { "name": "Giant, Hill", "CR": "7", "book": "Monster Manual I", "page": "121" },
  { "name": "Giant, Stone", "CR": "8", "book": "Monster Manual I", "page": "122" },
  { "name": "Giant, Storm", "CR": "13", "book": "Monster Manual I", "page": "123" },
  { "name": "Gibbering Mouther", "CR": "5", "book": "Monster Manual I", "page": "82" },
  { "name": "Githyanki", "CR": "3", "book": "Monster Manual I", "page": "83" },
  { "name": "Githzerai", "CR": "3", "book": "Monster Manual I", "page": "84" },
  { "name": "Gnoll", "CR": "1", "book": "Monster Manual I", "page": "85" },
  { "name": "Gnome", "CR": "1/2", "book": "Monster Manual I", "page": "85" },
  { "name": "Goblin", "CR": "1/3", "book": "Monster Manual I", "page": "86" },
  { "name": "Golem, Clay", "CR": "10", "book": "Monster Manual I", "page": "136" },
  { "name": "Golem, Flesh", "CR": "7", "book": "Monster Manual I", "page": "137" },
  { "name": "Golem, Iron", "CR": "13", "book": "Monster Manual I", "page": "138" },
  { "name": "Golem, Stone", "CR": "11", "book": "Monster Manual I", "page": "139" },
  { "name": "Gray Ooze", "CR": "4", "book": "Monster Manual I", "page": "87" },
  { "name": "Green Hag", "CR": "5", "book": "Monster Manual I", "page": "143" },
  { "name": "Grick", "CR": "3", "book": "Monster Manual I", "page": "88" },
  { "name": "Griffon", "CR": "4", "book": "Monster Manual I", "page": "88" },
  { "name": "Grimlock", "CR": "2", "book": "Monster Manual I", "page": "89" },
  { "name": "Halfling", "CR": "1/2", "book": "Monster Manual I", "page": "90" },
  { "name": "Harpy", "CR": "4", "book": "Monster Manual I", "page": "91" },
  { "name": "Hell Hound", "CR": "3", "book": "Monster Manual I", "page": "92" },
  { "name": "Hieracosphinx", "CR": "7", "book": "Monster Manual I", "page": "93" },
  { "name": "Hippogriff", "CR": "2", "book": "Monster Manual I", "page": "94" },
  { "name": "Homunculus", "CR": "1", "book": "Monster Manual I", "page": "95" },
  { "name": "Howler", "CR": "3", "book": "Monster Manual I", "page": "96" },
  { "name": "Hydra", "CR": "4", "book": "Monster Manual I", "page": "97" },
  { "name": "Chimera, Cryohydra", "CR": "7", "book": "Monster Manual I", "page": "98" },
  { "name": "Invisible Stalker", "CR": "7", "book": "Monster Manual I", "page": "99" },
  { "name": "Iron Cobra", "CR": "2", "book": "Monster Manual I", "page": "100" },
  { "name": "Kobold", "CR": "1/4", "book": "Monster Manual I", "page": "101" },
  { "name": "Krenshar", "CR": "1", "book": "Monster Manual I", "page": "102" },
  { "name": "Kuo-toa", "CR": "2", "book": "Monster Manual I", "page": "103" },
  { "name": "Lammasu", "CR": "7", "book": "Monster Manual I", "page": "104" },
  { "name": "Lamia", "CR": "6", "book": "Monster Manual I", "page": "105" },
  { "name": "Lich", "CR": "Varies", "book": "Monster Manual I", "page": "106" },
  { "name": "Lion", "CR": "3", "book": "Monster Manual I", "page": "108" },
  { "name": "Lizard", "CR": "1/6", "book": "Monster Manual I", "page": "108" },
  { "name": "Lizardfolk", "CR": "1", "book": "Monster Manual I", "page": "109" },
  { "name": "Locathah", "CR": "1", "book": "Monster Manual I", "page": "110" },
  { "name": "Lycanthrope, Werebear", "CR": "5", "book": "Monster Manual I", "page": "111" },
  { "name": "Lycanthrope, Wereboar", "CR": "4", "book": "Monster Manual I", "page": "112" },
  { "name": "Lycanthrope, Wererat", "CR": "2", "book": "Monster Manual I", "page": "113" },
  { "name": "Lycanthrope, Werewolf", "CR": "3", "book": "Monster Manual I", "page": "114" },
  { "name": "Magmin", "CR": "3", "book": "Monster Manual I", "page": "115" },
  { "name": "Manticore", "CR": "5", "book": "Monster Manual I", "page": "116" },
  { "name": "Medusa", "CR": "7", "book": "Monster Manual I", "page": "117" },
  { "name": "Mephit (various types)", "CR": "3", "book": "Monster Manual I", "page": "118" },
  { "name": "Merfolk", "CR": "1/2", "book": "Monster Manual I", "page": "120" },
  { "name": "Mimic", "CR": "4", "book": "Monster Manual I", "page": "121" },
  { "name": "Mind Flayer", "CR": "8", "book": "Monster Manual I", "page": "122" },
  { "name": "Minotaur", "CR": "4", "book": "Monster Manual I", "page": "123" },
  { "name": "Mohrg", "CR": "8", "book": "Monster Manual I", "page": "124" },
  { "name": "Mummy", "CR": "5", "book": "Monster Manual I", "page": "125" },
  { "name": "Naga, Dark", "CR": "7", "book": "Monster Manual I", "page": "126" },
  { "name": "Naga, Guardian", "CR": "10", "book": "Monster Manual I", "page": "127" },
  { "name": "Naga, Spirit", "CR": "9", "book": "Monster Manual I", "page": "128" },
  { "name": "Naga, Water", "CR": "7", "book": "Monster Manual I", "page": "129" },
  { "name": "Night Hag", "CR": "9", "book": "Monster Manual I", "page": "130" },
  { "name": "Nightmare", "CR": "5", "book": "Monster Manual I", "page": "131" },
  { "name": "Nymph", "CR": "7", "book": "Monster Manual I", "page": "132" },
  { "name": "Octopus", "CR": "1", "book": "Monster Manual I", "page": "133" },
  { "name": "Octopus, Giant", "CR": "8", "book": "Monster Manual I", "page": "134" },
  { "name": "Ogre", "CR": "3", "book": "Monster Manual I", "page": "135" },
  { "name": "Ogre Mage", "CR": "8", "book": "Monster Manual I", "page": "136" },
  { "name": "Ooze, Black Pudding", "CR": "10", "book": "Monster Manual I", "page": "137" },
  { "name": "Ooze, Gelatinous Cube", "CR": "3", "book": "Monster Manual I", "page": "138" },
  { "name": "Ooze, Gray", "CR": "4", "book": "Monster Manual I", "page": "139" },
  { "name": "Ooze, Ochre Jelly", "CR": "5", "book": "Monster Manual I", "page": "140" },
  { "name": "Orc", "CR": "1/2", "book": "Monster Manual I", "page": "141" },
  { "name": "Otyugh", "CR": "4", "book": "Monster Manual I", "page": "142" },
  { "name": "Owlbear", "CR": "4", "book": "Monster Manual I", "page": "143" },
  { "name": "Pegasus", "CR": "3", "book": "Monster Manual I", "page": "144" },
  { "name": "Phantom Fungus", "CR": "3", "book": "Monster Manual I", "page": "145" },
  { "name": "Phase Spider", "CR": "5", "book": "Monster Manual I", "page": "146" },
  { "name": "Planetar", "CR": "16", "book": "Monster Manual I", "page": "147" },
  { "name": "Purple Worm", "CR": "12", "book": "Monster Manual I", "page": "148" },
  { "name": "Rakshasa", "CR": "10", "book": "Monster Manual I", "page": "149" },
  { "name": "Rast", "CR": "5", "book": "Monster Manual I", "page": "150" },
  { "name": "Ravid", "CR": "5", "book": "Monster Manual I", "page": "151" },
  { "name": "Rhinoceros", "CR": "4", "book": "Monster Manual I", "page": "152" },
  { "name": "Roc", "CR": "9", "book": "Monster Manual I", "page": "153" },
  { "name": "Roper", "CR": "12", "book": "Monster Manual I", "page": "154" },
  { "name": "Rust Monster", "CR": "3", "book": "Monster Manual I", "page": "155" },
  { "name": "Sahuagin", "CR": "2", "book": "Monster Manual I", "page": "156" },
  { "name": "Salamander, Average", "CR": "5", "book": "Monster Manual I", "page": "157" },
  { "name": "Salamander, Flamebrother", "CR": "3", "book": "Monster Manual I", "page": "157" },
  { "name": "Salamander, Noble", "CR": "7", "book": "Monster Manual I", "page": "157" },
  { "name": "Satyr", "CR": "2", "book": "Monster Manual I", "page": "158" },
  { "name": "Scorpion, Monstrous Small", "CR": "1/2", "book": "Monster Manual I", "page": "159" },
  { "name": "Scorpion, Monstrous Medium", "CR": "1", "book": "Monster Manual I", "page": "159" },
  { "name": "Scorpion, Monstrous Large", "CR": "3", "book": "Monster Manual I", "page": "159" },
  { "name": "Scorpion, Monstrous Huge", "CR": "6", "book": "Monster Manual I", "page": "159" },
  { "name": "Scorpion, Monstrous Gargantuan", "CR": "9", "book": "Monster Manual I", "page": "159" },
  { "name": "Scorpion, Monstrous Colossal", "CR": "12", "book": "Monster Manual I", "page": "159" },
  { "name": "Sea Cat", "CR": "5", "book": "Monster Manual I", "page": "160" },
  { "name": "Shambling Mound", "CR": "6", "book": "Monster Manual I", "page": "161" },
  { "name": "Shark, Medium", "CR": "2", "book": "Monster Manual I", "page": "162" },
  { "name": "Shark, Large", "CR": "3", "book": "Monster Manual I", "page": "162" },
  { "name": "Shark, Huge", "CR": "6", "book": "Monster Manual I", "page": "162" },
  { "name": "Shark, Dire", "CR": "9", "book": "Monster Manual I", "page": "162" },
  { "name": "Shield Guardian", "CR": "8", "book": "Monster Manual I", "page": "163" },
  { "name": "Shocker Lizard", "CR": "2", "book": "Monster Manual I", "page": "164" },
  { "name": "Skeleton", "CR": "Varies", "book": "Monster Manual I", "page": "165" },
  { "name": "Skum", "CR": "3", "book": "Monster Manual I", "page": "166" },
  { "name": "Slaad, Blue", "CR": "7", "book": "Monster Manual I", "page": "167" },
  { "name": "Slaad, Death", "CR": "14", "book": "Monster Manual I", "page": "168" },
  { "name": "Slaad, Gray", "CR": "10", "book": "Monster Manual I", "page": "169" },
  { "name": "Slaad, Green", "CR": "8", "book": "Monster Manual I", "page": "170" },
  { "name": "Slaad, Red", "CR": "5", "book": "Monster Manual I", "page": "171" },
  { "name": "Slaad, White", "CR": "6", "book": "Monster Manual I", "page": "172" },
  { "name": "Spectre", "CR": "7", "book": "Monster Manual I", "page": "173" },
  { "name": "Sphinx, Androsphinx", "CR": "9", "book": "Monster Manual I", "page": "174" },
  { "name": "Sphinx, Criosphinx", "CR": "5", "book": "Monster Manual I", "page": "175" },
  { "name": "Sphinx, Gynosphinx", "CR": "8", "book": "Monster Manual I", "page": "176" },
  { "name": "Sphinx, Hieracosphinx", "CR": "7", "book": "Monster Manual I", "page": "177" },
  { "name": "Spider, Monstrous Small", "CR": "1/2", "book": "Monster Manual I", "page": "178" },
  { "name": "Spider, Monstrous Medium", "CR": "1", "book": "Monster Manual I", "page": "178" },
  { "name": "Spider, Monstrous Large", "CR": "3", "book": "Monster Manual I", "page": "178" },
  { "name": "Spider, Monstrous Huge", "CR": "5", "book": "Monster Manual I", "page": "178" },
  { "name": "Spider, Monstrous Gargantuan", "CR": "7", "book": "Monster Manual I", "page": "178" },
  { "name": "Spider, Monstrous Colossal", "CR": "10", "book": "Monster Manual I", "page": "178" },
  { "name": "Sprite", "CR": "1", "book": "Monster Manual I", "page": "179" },
  { "name": "Sprite, Grig", "CR": "1", "book": "Monster Manual I", "page": "180" },
  { "name": "Sprite, Nixie", "CR": "1", "book": "Monster Manual I", "page": "181" },
  { "name": "Sprite, Pixie", "CR": "4", "book": "Monster Manual I", "page": "182" },
  { "name": "Squid", "CR": "4", "book": "Monster Manual I", "page": "183" },
  { "name": "Squid, Giant", "CR": "9", "book": "Monster Manual I", "page": "183" },
  { "name": "Stirge", "CR": "1/2", "book": "Monster Manual I", "page": "184" },
  { "name": "Tarrasque", "CR": "20", "book": "Monster Manual I", "page": "185" },
  { "name": "Tendriculos", "CR": "6", "book": "Monster Manual I", "page": "186" },
  { "name": "Thoqqua", "CR": "2", "book": "Monster Manual I", "page": "187" },
  { "name": "Tiger", "CR": "4", "book": "Monster Manual I", "page": "188" },
  { "name": "Tiger, Dire", "CR": "8", "book": "Monster Manual I", "page": "188" },
  { "name": "Tojanida, Juvenile", "CR": "3", "book": "Monster Manual I", "page": "189" },
  { "name": "Tojanida, Adult", "CR": "7", "book": "Monster Manual I", "page": "189" },
  { "name": "Tojanida, Elder", "CR": "10", "book": "Monster Manual I", "page": "189" },
  { "name": "Troll", "CR": "5", "book": "Monster Manual I", "page": "190" },
  { "name": "Tyrannosaurus", "CR": "8", "book": "Monster Manual I", "page": "191" },
  { "name": "Unicorn", "CR": "3", "book": "Monster Manual I", "page": "192" },
  //Monster Manual I above this line
  { "name": "Abishai, Black", "CR": "3", "book": "Monster Manual II", "page": "6" },
  { "name": "Abishai, Blue", "CR": "5", "book": "Monster Manual II", "page": "6" },
  { "name": "Abishai, Green", "CR": "7", "book": "Monster Manual II", "page": "6" },
  { "name": "Abishai, Red", "CR": "9", "book": "Monster Manual II", "page": "6" },
  { "name": "Abishai, White", "CR": "1", "book": "Monster Manual II", "page": "6" },
  { "name": "Air Weird", "CR": "11", "book": "Monster Manual II", "page": "8" },
  { "name": "Alaghi", "CR": "5", "book": "Monster Manual II", "page": "10" },
  { "name": "Alcor", "CR": "12", "book": "Monster Manual II", "page": "12" },
  { "name": "Ambush Drake", "CR": "3", "book": "Monster Manual II", "page": "14" },
  { "name": "Anakore", "CR": "4", "book": "Monster Manual II", "page": "16" },
  { "name": "Androsphinx", "CR": "9", "book": "Monster Manual II", "page": "18" },
  { "name": "Angazhan", "CR": "18", "book": "Monster Manual II", "page": "20" },
  { "name": "Armanite", "CR": "6", "book": "Monster Manual II", "page": "22" },
  { "name": "Ash Rat", "CR": "1/2", "book": "Monster Manual II", "page": "24" },
  { "name": "Asperi", "CR": "3", "book": "Monster Manual II", "page": "26" },
  { "name": "Athach", "CR": "10", "book": "Monster Manual II", "page": "28" },
  { "name": "Avolakia", "CR": "9", "book": "Monster Manual II", "page": "30" },
  { "name": "Azerblood", "CR": "6", "book": "Monster Manual II", "page": "32" },
  { "name": "Azerwarrior", "CR": "3", "book": "Monster Manual II", "page": "32" },
  { "name": "Balhannoth", "CR": "11", "book": "Monster Manual II", "page": "34" },
  { "name": "Banshrae", "CR": "5", "book": "Monster Manual II", "page": "36" },
  { "name": "Barghest, Greater", "CR": "6", "book": "Monster Manual II", "page": "38" },
  { "name": "Barghest, Lesser", "CR": "4", "book": "Monster Manual II", "page": "38" },
  { "name": "Bariaur", "CR": "2", "book": "Monster Manual II", "page": "40" },
  { "name": "Basilisk, Greater", "CR": "7", "book": "Monster Manual II", "page": "42" },
  { "name": "Bat, Hell", "CR": "2", "book": "Monster Manual II", "page": "44" },
  { "name": "Battle Horror", "CR": "5", "book": "Monster Manual II", "page": "46" },
  { "name": "Beetle, Bombardier", "CR": "2", "book": "Monster Manual II", "page": "48" },
  { "name": "Beetle, Fire", "CR": "1", "book": "Monster Manual II", "page": "48" },
  { "name": "Belker, Smoke", "CR": "6", "book": "Monster Manual II", "page": "50" },
  { "name": "Bhut", "CR": "6", "book": "Monster Manual II", "page": "52" },
  { "name": "Blackspawn Stalker", "CR": "7", "book": "Monster Manual II", "page": "54" },
  { "name": "Blindheim", "CR": "2", "book": "Monster Manual II", "page": "56" },
  { "name": "Blood Ape", "CR": "3", "book": "Monster Manual II", "page": "58" },
  { "name": "Bloodmote Cloud", "CR": "3", "book": "Monster Manual II", "page": "60" },
  { "name": "Blue Slaad", "CR": "7", "book": "Monster Manual II", "page": "62" },
  { "name": "Bone Claw", "CR": "12", "book": "Monster Manual II", "page": "64" },
  { "name": "Bone Naga", "CR": "8", "book": "Monster Manual II", "page": "66" },
  { "name": "Bone Swarm", "CR": "5", "book": "Monster Manual II", "page": "68" },
  { "name": "Brachyurus", "CR": "15", "book": "Monster Manual II", "page": "70" },
  { "name": "Brass Minotaur", "CR": "7", "book": "Monster Manual II", "page": "72" },
  { "name": "Brine Ooze", "CR": "6", "book": "Monster Manual II", "page": "74" },
  { "name": "Brood Keeper", "CR": "12", "book": "Monster Manual II", "page": "76" },
  { "name": "Brood Swarm", "CR": "5", "book": "Monster Manual II", "page": "76" },
  { "name": "Bulette, Landshark", "CR": "7", "book": "Monster Manual II", "page": "78" },
  { "name": "Cadaver Collector", "CR": "9", "book": "Monster Manual II", "page": "80" },
  { "name": "Cave Fisher", "CR": "4", "book": "Monster Manual II", "page": "82" },
  { "name": "Centaur, Desert", "CR": "4", "book": "Monster Manual II", "page": "84" },
  { "name": "Chaos Beast", "CR": "7", "book": "Monster Manual II", "page": "86" },
  { "name": "Chitine", "CR": "2", "book": "Monster Manual II", "page": "88" },
  { "name": "Choker, Lesser", "CR": "1", "book": "Monster Manual II", "page": "90" },
  { "name": "Cloaker Lord", "CR": "9", "book": "Monster Manual II", "page": "92" },
  { "name": "Corpse Gatherer", "CR": "13", "book": "Monster Manual II", "page": "94" },
  { "name": "Crimson Death", "CR": "12", "book": "Monster Manual II", "page": "96" },
  { "name": "Crysmal", "CR": "5", "book": "Monster Manual II", "page": "98" },
  { "name": "Cynidicean", "CR": "2", "book": "Monster Manual II", "page": "100" },
  { "name": "Darkmantle, Greater", "CR": "3", "book": "Monster Manual II", "page": "102" },
  { "name": "Deathbringer", "CR": "17", "book": "Monster Manual II", "page": "104" },
  { "name": "Deathkiss", "CR": "9", "book": "Monster Manual II", "page": "106" },
  { "name": "Deep Dragon, Young", "CR": "5", "book": "Monster Manual II", "page": "108" },
  { "name": "Deep Dragon, Adult", "CR": "13", "book": "Monster Manual II", "page": "108" },
  { "name": "Deep Dragon, Ancient", "CR": "18", "book": "Monster Manual II", "page": "108" },
  { "name": "Demon, Maurezhi", "CR": "7", "book": "Monster Manual II", "page": "110" },
  { "name": "Demon, Wastrilith", "CR": "12", "book": "Monster Manual II", "page": "112" },
  { "name": "Demonspawn of Juiblex", "CR": "5", "book": "Monster Manual II", "page": "114" },
  { "name": "Desmodu, Guard", "CR": "3", "book": "Monster Manual II", "page": "116" },
  { "name": "Desmodu, Champion", "CR": "6", "book": "Monster Manual II", "page": "116" },
  { "name": "Desmodu, Warleader", "CR": "9", "book": "Monster Manual II", "page": "116" },
  { "name": "Desmodu, Sage", "CR": "7", "book": "Monster Manual II", "page": "116" },
  { "name": "Destrachan, Elder", "CR": "7", "book": "Monster Manual II", "page": "118" },
  { "name": "Dhaerow", "CR": "3", "book": "Monster Manual II", "page": "120" },
  { "name": "Dire Hawk", "CR": "3", "book": "Monster Manual II", "page": "122" },
  { "name": "Dire Horse", "CR": "4", "book": "Monster Manual II", "page": "124" },
  { "name": "Displacer Beast Pack Lord", "CR": "6", "book": "Monster Manual II", "page": "126" },
  { "name": "Doom Guard", "CR": "10", "book": "Monster Manual II", "page": "128" },
  { "name": "Dracolisk", "CR": "9", "book": "Monster Manual II", "page": "130" },
  { "name": "Dragonfish", "CR": "2", "book": "Monster Manual II", "page": "132" },
  { "name": "Dread Guard", "CR": "4", "book": "Monster Manual II", "page": "134" },
  { "name": "Dune Stalker", "CR": "5", "book": "Monster Manual II", "page": "136" },
  { "name": "Dwarf Ancestor", "CR": "14", "book": "Monster Manual II", "page": "138" },
  { "name": "Earth Weird", "CR": "11", "book": "Monster Manual II", "page": "140" },
  { "name": "Elder Serpent", "CR": "13", "book": "Monster Manual II", "page": "142" },
  { "name": "Elder Treant", "CR": "12", "book": "Monster Manual II", "page": "144" },
  { "name": "Ethereal Slayer", "CR": "10", "book": "Monster Manual II", "page": "146" },
  { "name": "Ethereal Stalker", "CR": "7", "book": "Monster Manual II", "page": "148" },
  { "name": "Fael", "CR": "5", "book": "Monster Manual II", "page": "150" },
  { "name": "Famine Spirit", "CR": "9", "book": "Monster Manual II", "page": "152" },
  { "name": "Feral Minotaur", "CR": "4", "book": "Monster Manual II", "page": "154" },
  { "name": "Feytouched", "CR": "3", "book": "Monster Manual II", "page": "156" },
  { "name": "Fiendwurm", "CR": "15", "book": "Monster Manual II", "page": "158" },
  { "name": "Fire Weird", "CR": "11", "book": "Monster Manual II", "page": "160" },
  { "name": "Flame Snake", "CR": "4", "book": "Monster Manual II", "page": "162" },
  { "name": "Flamebrother Salamander", "CR": "3", "book": "Monster Manual II", "page": "164" },
  { "name": "Flind", "CR": "2", "book": "Monster Manual II", "page": "166" },
  { "name": "Forest Sloth", "CR": "6", "book": "Monster Manual II", "page": "168" },
  { "name": "Frost Worm Swarm", "CR": "14", "book": "Monster Manual II", "page": "170" },
  { "name": "Frost Weird", "CR": "11", "book": "Monster Manual II", "page": "172" },
  { "name": "Frostwind Virago", "CR": "12", "book": "Monster Manual II", "page": "174" },
  { "name": "Fury", "CR": "8", "book": "Monster Manual II", "page": "176" },
  { "name": "Galeb Duhr Elder", "CR": "11", "book": "Monster Manual II", "page": "178" },
  { "name": "Gambol", "CR": "5", "book": "Monster Manual II", "page": "180" },
  { "name": "Gargantuan Monstrous Centipede", "CR": "10", "book": "Monster Manual II", "page": "182" },
  { "name": "Gargantuan Monstrous Spider", "CR": "8", "book": "Monster Manual II", "page": "184" },
  { "name": "Garnag", "CR": "7", "book": "Monster Manual II", "page": "186" },
  { "name": "Gem Scarab", "CR": "4", "book": "Monster Manual II", "page": "188" },
  { "name": "Ghost Brute", "CR": "7", "book": "Monster Manual II", "page": "190" },
  { "name": "Ghost Mount", "CR": "5", "book": "Monster Manual II", "page": "192" },
  { "name": "Gibbering Orb", "CR": "12", "book": "Monster Manual II", "page": "194" },
  { "name": "Gloom", "CR": "10", "book": "Monster Manual II", "page": "196" },
  { "name": "Golem, Prismatic", "CR": "18", "book": "Monster Manual II", "page": "198" },
  { "name": "Goreclaw", "CR": "8", "book": "Monster Manual II", "page": "200" },
  { "name": "Greenvise", "CR": "6", "book": "Monster Manual II", "page": "202" },
  { "name": "Grimalkin", "CR": "3", "book": "Monster Manual II", "page": "204" },
  { "name": "Grisgol", "CR": "12", "book": "Monster Manual II", "page": "206" },
  { "name": "Grue, Chaggrin", "CR": "2", "book": "Monster Manual II", "page": "208" },
  { "name": "Grue, Harginn", "CR": "3", "book": "Monster Manual II", "page": "208" },
  { "name": "Grue, Ildriss", "CR": "2", "book": "Monster Manual II", "page": "209" },
  { "name": "Grue, Vargouille", "CR": "1", "book": "Monster Manual II", "page": "209" },
  { "name": "Guardian Spirit", "CR": "5", "book": "Monster Manual II", "page": "210" },
  { "name": "Ha-Naga", "CR": "14", "book": "Monster Manual II", "page": "212" },
  { "name": "Harginn", "CR": "3", "book": "Monster Manual II", "page": "214" },
  { "name": "Hellcat", "CR": "6", "book": "Monster Manual II", "page": "216" },
  { "name": "Hellwasp Swarm", "CR": "6", "book": "Monster Manual II", "page": "218" },
  { "name": "Hoary Hunter", "CR": "10", "book": "Monster Manual II", "page": "220" },
  { "name": "Horned Devil", "CR": "16", "book": "Monster Manual II", "page": "222" },
  { "name": "Howler Wasp", "CR": "2", "book": "Monster Manual II", "page": "224" },
  { "name": "Ice Golem", "CR": "6", "book": "Monster Manual II", "page": "226" },
  { "name": "Ildriss", "CR": "2", "book": "Monster Manual II", "page": "228" },
  { "name": "Inphidian", "CR": "4", "book": "Monster Manual II", "page": "230" },
  { "name": "Iron Golem Juggernaut", "CR": "19", "book": "Monster Manual II", "page": "232" },
  { "name": "Jackal Lord", "CR": "8", "book": "Monster Manual II", "page": "234" },
  { "name": "Janni", "CR": "5", "book": "Monster Manual II", "page": "236" },
  { "name": "Jerren", "CR": "1", "book": "Monster Manual II", "page": "238" },
  { "name": "Kaorti", "CR": "5", "book": "Monster Manual II", "page": "240" },
  { "name": "Khaasta", "CR": "6", "book": "Monster Manual II", "page": "242" },
  { "name": "Klurichir", "CR": "21", "book": "Monster Manual II", "page": "244" },
  { "name": "Kocrachon", "CR": "6", "book": "Monster Manual II", "page": "246" },
  { "name": "Kolyarut", "CR": "12", "book": "Monster Manual II", "page": "248" },
  { "name": "Krenshar, Greater", "CR": "3", "book": "Monster Manual II", "page": "250" },
  { "name": "Kyton", "CR": "6", "book": "Monster Manual II", "page": "252" },
  { "name": "Lammasu, Greater", "CR": "10", "book": "Monster Manual II", "page": "254" },
  { "name": "Lavawight", "CR": "10", "book": "Monster Manual II", "page": "256" },
  { "name": "Leaf Horror", "CR": "4", "book": "Monster Manual II", "page": "258" },
  { "name": "Lesser Death", "CR": "10", "book": "Monster Manual II", "page": "260" },
  { "name": "Lichfiend", "CR": "15", "book": "Monster Manual II", "page": "262" },
  { "name": "Living Fireball", "CR": "6", "book": "Monster Manual II", "page": "264" },
  { "name": "Living Spell", "CR": "Varies", "book": "Monster Manual II", "page": "266" },
  { "name": "Lurking Strangler", "CR": "2", "book": "Monster Manual II", "page": "268" },
  { "name": "Magma Hurler", "CR": "5", "book": "Monster Manual II", "page": "270" },
  { "name": "Moonbeast", "CR": "12", "book": "Monster Manual II", "page": "272" },
  { "name": "Mountain Roper", "CR": "9", "book": "Monster Manual II", "page": "274" },
  { "name": "Murderwrack", "CR": "6", "book": "Monster Manual II", "page": "276" },
  { "name": "Needlefolk", "CR": "2", "book": "Monster Manual II", "page": "278" },
  { "name": "Needlefolk Slasher", "CR": "3", "book": "Monster Manual II", "page": "279" },
  { "name": "Nightmare Beast", "CR": "17", "book": "Monster Manual II", "page": "280" },
  { "name": "Nightmare Beast Larva", "CR": "9", "book": "Monster Manual II", "page": "280" },
  { "name": "Nightmare Beast Spawn", "CR": "4", "book": "Monster Manual II", "page": "281" },
  { "name": "Ocean Strider", "CR": "9", "book": "Monster Manual II", "page": "282" },
  { "name": "Phase Wasp", "CR": "3", "book": "Monster Manual II", "page": "284" },
  { "name": "Phoenix", "CR": "16", "book": "Monster Manual II", "page": "286" },
  { "name": "Planetouched", "CR": "2", "book": "Monster Manual II", "page": "288" },
  { "name": "Psurlon", "CR": "5", "book": "Monster Manual II", "page": "290" },
  { "name": "Ragewind", "CR": "13", "book": "Monster Manual II", "page": "292" },
  { "name": "Raggamoffyn, Tatterdemanimal", "CR": "2", "book": "Monster Manual II", "page": "294" },
  { "name": "Raggamoffyn, Chaine", "CR": "4", "book": "Monster Manual II", "page": "294" },
  { "name": "Raggamoffyn, Filth", "CR": "6", "book": "Monster Manual II", "page": "295" },
  { "name": "Rampager", "CR": "16", "book": "Monster Manual II", "page": "296" },
  { "name": "Razor Boar", "CR": "4", "book": "Monster Manual II", "page": "298" },
  { "name": "Ravenous Template", "CR": "Varies", "book": "Monster Manual II", "page": "300" },
  { "name": "Reason Stealer", "CR": "7", "book": "Monster Manual II", "page": "302" },
  { "name": "Red Sundew", "CR": "3", "book": "Monster Manual II", "page": "304" },
  { "name": "Rejkar", "CR": "5", "book": "Monster Manual II", "page": "306" },
  { "name": "Rukarazyll", "CR": "8", "book": "Monster Manual II", "page": "308" },
  { "name": "Sand Giant", "CR": "11", "book": "Monster Manual II", "page": "310" },
  { "name": "Sand Hunter", "CR": "6", "book": "Monster Manual II", "page": "312" },
  { "name": "Savage Template", "CR": "Varies", "book": "Monster Manual II", "page": "314" },
  { "name": "Shadow Spider", "CR": "6", "book": "Monster Manual II", "page": "316" },
  { "name": "Shadowrath", "CR": "12", "book": "Monster Manual II", "page": "318" },
  { "name": "Shard", "CR": "4", "book": "Monster Manual II", "page": "320" },
  { "name": "Shimmerling Swarm", "CR": "6", "book": "Monster Manual II", "page": "322" },
  { "name": "Skeroloth", "CR": "9", "book": "Monster Manual II", "page": "324" },
  { "name": "Spawn of Kyuss", "CR": "5", "book": "Monster Manual II", "page": "326" },
  { "name": "Spell Collector", "CR": "14", "book": "Monster Manual II", "page": "328" },
  { "name": "Spellstitched Creature Template", "CR": "Varies", "book": "Monster Manual II", "page": "330" },
  { "name": "Spiderstone Golem", "CR": "10", "book": "Monster Manual II", "page": "332" },
  { "name": "Spiker", "CR": "2", "book": "Monster Manual II", "page": "334" },
  { "name": "Splinterwaif", "CR": "4", "book": "Monster Manual II", "page": "336" },
  { "name": "Sporebat", "CR": "1", "book": "Monster Manual II", "page": "338" },
  { "name": "Stonewalker", "CR": "7", "book": "Monster Manual II", "page": "340" },
  { "name": "Striped Toadstool", "CR": "1/2", "book": "Monster Manual II", "page": "342" },
  { "name": "Styx Devil", "CR": "15", "book": "Monster Manual II", "page": "344" },
  { "name": "Stheno", "CR": "6", "book": "Monster Manual II", "page": "346" },
  { "name": "Sulak", "CR": "9", "book": "Monster Manual II", "page": "348" },
  { "name": "Sunfly Swarm", "CR": "3", "book": "Monster Manual II", "page": "350" },
  { "name": "Swarm Shifter Template", "CR": "Varies", "book": "Monster Manual II", "page": "352" },
  { "name": "Sylph", "CR": "4", "book": "Monster Manual II", "page": "354" },
  { "name": "Tempest", "CR": "13", "book": "Monster Manual II", "page": "356" },
  { "name": "Titanic Creature Template", "CR": "Varies", "book": "Monster Manual II", "page": "358" },
  { "name": "True Ghoul", "CR": "10", "book": "Monster Manual II", "page": "360" },
  { "name": "Tsochar", "CR": "5", "book": "Monster Manual II", "page": "362" },
  { "name": "Tzakandi", "CR": "6", "book": "Monster Manual II", "page": "364" },
  { "name": "Umbral Blot", "CR": "21", "book": "Monster Manual II", "page": "366" },
  { "name": "Uvuudaum", "CR": "20", "book": "Monster Manual II", "page": "368" },
  { "name": "Vaprak the Destroyer", "CR": "19", "book": "Monster Manual II", "page": "370" },
  { "name": "Varrangoin, Lesser", "CR": "6", "book": "Monster Manual II", "page": "372" },
  { "name": "Varrangoin, Greater", "CR": "10", "book": "Monster Manual II", "page": "373" },
  { "name": "Winterspawn", "CR": "7", "book": "Monster Manual II", "page": "374" },
  { "name": "Xaren", "CR": "3", "book": "Monster Manual II", "page": "376" },
  { "name": "Xixchil", "CR": "5", "book": "Monster Manual II", "page": "378" },
  { "name": "Xorn, Elder", "CR": "8", "book": "Monster Manual II", "page": "380" },
  { "name": "Xorn, Greater", "CR": "10", "book": "Monster Manual II", "page": "381" },
  { "name": "Yak Folk", "CR": "6", "book": "Monster Manual II", "page": "382" },
  { "name": "Yeth Hound", "CR": "3", "book": "Monster Manual II", "page": "384" },
  { "name": "Yugoloth, Canoloth", "CR": "6", "book": "Monster Manual II", "page": "386" },
  { "name": "Yugoloth, Marraenoloth", "CR": "7", "book": "Monster Manual II", "page": "387" },
  { "name": "Yugoloth, Nycaloth", "CR": "11", "book": "Monster Manual II", "page": "388" },
  { "name": "Zern", "CR": "6", "book": "Monster Manual II", "page": "390" },
  { "name": "Zodar", "CR": "15", "book": "Monster Manual II", "page": "392" },
  { "name": "Zorbo", "CR": "2", "book": "Monster Manual II", "page": "394" },
  //Monster Manual II above
  { "name": "Abyssal Ghoul", "CR": "3", "book": "Monster Manual III", "page": "8" },
  { "name": "Adaru", "CR": "10", "book": "Monster Manual III", "page": "10" },
  { "name": "Ahuizotl", "CR": "4", "book": "Monster Manual III", "page": "12" },
  { "name": "Air Elemental Monolith", "CR": "17", "book": "Monster Manual III", "page": "14" },
  { "name": "Ape, Dire", "CR": "7", "book": "Monster Manual III", "page": "16" },
  { "name": "Arcadian Avenger", "CR": "5", "book": "Monster Manual III", "page": "18" },
  { "name": "Armand", "CR": "2", "book": "Monster Manual III", "page": "20" },
  { "name": "Ash Rat", "CR": "1/2", "book": "Monster Manual III", "page": "22" },
  { "name": "Asrai", "CR": "1", "book": "Monster Manual III", "page": "24" },
  { "name": "Barghest, Greater", "CR": "6", "book": "Monster Manual III", "page": "26" },
  { "name": "Barghest, Lesser", "CR": "4", "book": "Monster Manual III", "page": "26" },
  { "name": "Battle Titan", "CR": "20", "book": "Monster Manual III", "page": "28" },
  { "name": "Bearhound", "CR": "5", "book": "Monster Manual III", "page": "30" },
  { "name": "Beetle, Fire", "CR": "1", "book": "Monster Manual III", "page": "32" },
  { "name": "Beetle, Slicer", "CR": "2", "book": "Monster Manual III", "page": "34" },
  { "name": "Beholderkin, Death Kiss", "CR": "9", "book": "Monster Manual III", "page": "36" },
  { "name": "Braxat", "CR": "9", "book": "Monster Manual III", "page": "38" },
  { "name": "Cave Tyrant", "CR": "6", "book": "Monster Manual III", "page": "40" },
  { "name": "Celestial Charger", "CR": "8", "book": "Monster Manual III", "page": "42" },
  { "name": "Chaos Roc", "CR": "14", "book": "Monster Manual III", "page": "44" },
  { "name": "Chimera, Shadow", "CR": "8", "book": "Monster Manual III", "page": "46" },
  { "name": "Chraal", "CR": "9", "book": "Monster Manual III", "page": "48" },
  { "name": "Chwidencha", "CR": "5", "book": "Monster Manual III", "page": "50" },
  { "name": "Cliff Giant", "CR": "11", "book": "Monster Manual III", "page": "52" },
  { "name": "Clockwork Horror", "CR": "4", "book": "Monster Manual III", "page": "54" },
  { "name": "Cloud Ray", "CR": "15", "book": "Monster Manual III", "page": "56" },
  { "name": "Corpse Gatherer", "CR": "13", "book": "Monster Manual III", "page": "58" },
  { "name": "Cursed One", "CR": "6", "book": "Monster Manual III", "page": "60" },
  { "name": "Dagorran", "CR": "3", "book": "Monster Manual III", "page": "62" },
  { "name": "Darkweaver", "CR": "12", "book": "Monster Manual III", "page": "64" },
  { "name": "Death Giant", "CR": "18", "book": "Monster Manual III", "page": "66" },
  { "name": "Demon, Armanite", "CR": "6", "book": "Monster Manual III", "page": "68" },
  { "name": "Demon, Bulezau", "CR": "6", "book": "Monster Manual III", "page": "70" },
  { "name": "Demon, Rutterkin", "CR": "5", "book": "Monster Manual III", "page": "72" },
  { "name": "Demon, Wastrilith", "CR": "12", "book": "Monster Manual III", "page": "74" },
  { "name": "Desmodu", "CR": "3-9", "book": "Monster Manual III", "page": "76" },
  { "name": "Devil, Harvester", "CR": "10", "book": "Monster Manual III", "page": "78" },
  { "name": "Devil, Steel", "CR": "11", "book": "Monster Manual III", "page": "80" },
  { "name": "Digester", "CR": "6", "book": "Monster Manual III", "page": "82" },
  { "name": "Dire Hawk", "CR": "3", "book": "Monster Manual III", "page": "84" },
  { "name": "Dracotaur", "CR": "7", "book": "Monster Manual III", "page": "86" },
  { "name": "Dragon Eel", "CR": "12", "book": "Monster Manual III", "page": "88" },
  { "name": "Dread Blossom Swarm", "CR": "6", "book": "Monster Manual III", "page": "90" },
  { "name": "Dread Wraith", "CR": "11", "book": "Monster Manual III", "page": "92" },
  { "name": "Dust Wight", "CR": "8", "book": "Monster Manual III", "page": "94" },
  { "name": "Earth Elemental Monolith", "CR": "17", "book": "Monster Manual III", "page": "96" },
  { "name": "Efreeti (Noble)", "CR": "12", "book": "Monster Manual III", "page": "98" },
  { "name": "Elder Brain", "CR": "20", "book": "Monster Manual III", "page": "100" },
  { "name": "Elemental Weirds (Air, Earth, Fire, Water)", "CR": "11", "book": "Monster Manual III", "page": "102" },
  { "name": "Embrac", "CR": "15", "book": "Monster Manual III", "page": "104" },
  { "name": "Eye of Fear and Flame", "CR": "12", "book": "Monster Manual III", "page": "106" },
  { "name": "Famine Spirit", "CR": "9", "book": "Monster Manual III", "page": "108" },
  { "name": "Fell Troll", "CR": "7", "book": "Monster Manual III", "page": "110" },
  { "name": "Filth Gnome", "CR": "3", "book": "Monster Manual III", "page": "112" },
  { "name": "Flame Snake", "CR": "4", "book": "Monster Manual III", "page": "114" },
  { "name": "Flesh Jelly", "CR": "6", "book": "Monster Manual III", "page": "116" },
  { "name": "Forest Troll", "CR": "6", "book": "Monster Manual III", "page": "118" },
  { "name": "Frostwind Virago", "CR": "12", "book": "Monster Manual III", "page": "120" },
  { "name": "Fury", "CR": "8", "book": "Monster Manual III", "page": "122" },
  { "name": "Gambol", "CR": "5", "book": "Monster Manual III", "page": "124" },
  { "name": "Gargantuan Monstrous Centipede", "CR": "10", "book": "Monster Manual III", "page": "126" },
  { "name": "Ghost Brute", "CR": "7", "book": "Monster Manual III", "page": "128" },
  { "name": "Glouras", "CR": "6", "book": "Monster Manual III", "page": "130" },
  { "name": "Golem, Runic", "CR": "10", "book": "Monster Manual III", "page": "132" },
  { "name": "Goristro", "CR": "19", "book": "Monster Manual III", "page": "134" },
  { "name": "Gravecrawler", "CR": "3", "book": "Monster Manual III", "page": "136" },
  { "name": "Grimalkin", "CR": "3", "book": "Monster Manual III", "page": "138" },
  { "name": "Grisgol", "CR": "12", "book": "Monster Manual III", "page": "140" },
  { "name": "Gruthluk", "CR": "4", "book": "Monster Manual III", "page": "142" },
  { "name": "Half-Golem (Template)", "CR": "Varies", "book": "Monster Manual III", "page": "144" },
  { "name": "Harrowblade", "CR": "6", "book": "Monster Manual III", "page": "146" },
  { "name": "Hellfire Wyrm", "CR": "18", "book": "Monster Manual III", "page": "148" },
  { "name": "Hellwasp Swarm", "CR": "6", "book": "Monster Manual III", "page": "150" },
  { "name": "Hook Horror, Greater", "CR": "6", "book": "Monster Manual III", "page": "152" },
  { "name": "Howler Wasp", "CR": "2", "book": "Monster Manual III", "page": "154" },
  { "name": "Ibrandlin", "CR": "7", "book": "Monster Manual III", "page": "156" },
  { "name": "Ice Devil", "CR": "13", "book": "Monster Manual III", "page": "158" },
  { "name": "Inphidian", "CR": "4", "book": "Monster Manual III", "page": "160" },
  { "name": "Ixitxachitl", "CR": "2", "book": "Monster Manual III", "page": "162" },
  { "name": "Jerren", "CR": "1", "book": "Monster Manual III", "page": "164" },
  { "name": "Khaasta", "CR": "6", "book": "Monster Manual III", "page": "166" },
  { "name": "Krenshar, Greater", "CR": "3", "book": "Monster Manual III", "page": "168" },
  { "name": "Kyton", "CR": "6", "book": "Monster Manual III", "page": "170" },
  { "name": "Lamia Matriarch", "CR": "8", "book": "Monster Manual III", "page": "172" },
  { "name": "Lavawight", "CR": "10", "book": "Monster Manual III", "page": "174" },
  { "name": "Leaf Horror", "CR": "4", "book": "Monster Manual III", "page": "176" },
  { "name": "Lichfiend", "CR": "15", "book": "Monster Manual III", "page": "178" },
  { "name": "Living Blasphemy", "CR": "14", "book": "Monster Manual III", "page": "180" },
  { "name": "Living Spell", "CR": "Varies", "book": "Monster Manual III", "page": "182" },
  { "name": "Maelephant", "CR": "10", "book": "Monster Manual III", "page": "184" },
  { "name": "Moonbeast", "CR": "12", "book": "Monster Manual III", "page": "186" },
  { "name": "Mountain Roper", "CR": "9", "book": "Monster Manual III", "page": "188" },
  { "name": "Murderwrack", "CR": "6", "book": "Monster Manual III", "page": "190" },
  { "name": "Needlefolk Slasher", "CR": "3", "book": "Monster Manual III", "page": "192" },
  { "name": "Nightmare Beast", "CR": "17", "book": "Monster Manual III", "page": "194" },
  { "name": "Ocean Strider", "CR": "9", "book": "Monster Manual III", "page": "196" },
  { "name": "Phase Wasp", "CR": "3", "book": "Monster Manual III", "page": "198" },
  { "name": "Phoenix", "CR": "16", "book": "Monster Manual III", "page": "200" },
  { "name": "Planetouched", "CR": "2", "book": "Monster Manual III", "page": "202" },
  { "name": "Psurlon", "CR": "5", "book": "Monster Manual III", "page": "204" },
  { "name": "Ragewind", "CR": "13", "book": "Monster Manual III", "page": "206" },
  { "name": "Raggamoffyn", "CR": "2-6", "book": "Monster Manual III", "page": "208" },
  { "name": "Rampager", "CR": "16", "book": "Monster Manual III", "page": "210" },
  { "name": "Reason Stealer", "CR": "7", "book": "Monster Manual III", "page": "212" },
  { "name": "Rejkar", "CR": "5", "book": "Monster Manual III", "page": "214" },
  { "name": "Sand Hunter", "CR": "6", "book": "Monster Manual III", "page": "216" },
  { "name": "Shadow Spider", "CR": "6", "book": "Monster Manual III", "page": "218" },
  { "name": "Spell Collector", "CR": "14", "book": "Monster Manual III", "page": "220" },
  { "name": "Spiker", "CR": "2", "book": "Monster Manual III", "page": "222" },
  { "name": "Splinterwaif", "CR": "4", "book": "Monster Manual III", "page": "224" },
  { "name": "Styx Devil", "CR": "15", "book": "Monster Manual III", "page": "226" },
  { "name": "Stheno", "CR": "6", "book": "Monster Manual III", "page": "228" },
  { "name": "Sulak", "CR": "9", "book": "Monster Manual III", "page": "230" },
  { "name": "Swarm Shifter (Template)", "CR": "Varies", "book": "Monster Manual III", "page": "232" },
  { "name": "Sylph", "CR": "4", "book": "Monster Manual III", "page": "234" },
  { "name": "Tempest", "CR": "13", "book": "Monster Manual III", "page": "236" },
  { "name": "True Ghoul", "CR": "10", "book": "Monster Manual III", "page": "238" },
  { "name": "Umbral Blot", "CR": "21", "book": "Monster Manual III", "page": "240" },
  { "name": "Uvuudaum", "CR": "20", "book": "Monster Manual III", "page": "242" },
  { "name": "Vampire Mind Flayer", "CR": "13", "book": "Monster Manual III", "page": "244" },
  { "name": "Varrangoin", "CR": "6-10", "book": "Monster Manual III", "page": "246" },
  { "name": "Winterspawn", "CR": "7", "book": "Monster Manual III", "page": "248" },
  { "name": "Xixchil", "CR": "5", "book": "Monster Manual III", "page": "250" },
  { "name": "Yak Folk", "CR": "6", "book": "Monster Manual III", "page": "252" },
  { "name": "Yeth Hound", "CR": "3", "book": "Monster Manual III", "page": "254" },
  { "name": "Yugoloth", "CR": "6-11", "book": "Monster Manual III", "page": "256" },
  { "name": "Zern", "CR": "6", "book": "Monster Manual III", "page": "258" },
  { "name": "Zodar", "CR": "15", "book": "Monster Manual III", "page": "260" },
  { "name": "Zorbo", "CR": "2", "book": "Monster Manual III", "page": "262" },
  //Monster Manual III above
  { "name": "Arcadian Avenger", "CR": "5", "book": "Monster Manual IV", "page": "6" },
  { "name": "Armand", "CR": "2", "book": "Monster Manual IV", "page": "8" },
  { "name": "Ash Rat", "CR": "1/2", "book": "Monster Manual IV", "page": "10" },
  { "name": "Battle Horror", "CR": "5", "book": "Monster Manual IV", "page": "12" },
  { "name": "Blackscale Lizardfolk", "CR": "3", "book": "Monster Manual IV", "page": "14" },
  { "name": "Blood Ape", "CR": "3", "book": "Monster Manual IV", "page": "16" },
  { "name": "Bloodstriker Thoqqua", "CR": "5", "book": "Monster Manual IV", "page": "18" },
  { "name": "Bonedrinker", "CR": "9", "book": "Monster Manual IV", "page": "20" },
  { "name": "Bone Naga", "CR": "8", "book": "Monster Manual IV", "page": "22" },
  { "name": "Bone Swarm", "CR": "5", "book": "Monster Manual IV", "page": "24" },
  { "name": "Cave Fisher", "CR": "4", "book": "Monster Manual IV", "page": "26" },
  { "name": "Chraal", "CR": "9", "book": "Monster Manual IV", "page": "28" },
  { "name": "Corollax", "CR": "1", "book": "Monster Manual IV", "page": "30" },
  { "name": "Dark Naga", "CR": "7", "book": "Monster Manual IV", "page": "32" },
  { "name": "Deep Dragon", "CR": "5-18", "book": "Monster Manual IV", "page": "34" },
  { "name": "Dread Ram", "CR": "6", "book": "Monster Manual IV", "page": "36" },
  { "name": "Dread Wraith", "CR": "11", "book": "Monster Manual IV", "page": "38" },
  { "name": "Dust Wight", "CR": "8", "book": "Monster Manual IV", "page": "40" },
  { "name": "Effigy Creature", "CR": "Varies", "book": "Monster Manual IV", "page": "42" },
  { "name": "Elf, Drow Warrior", "CR": "1", "book": "Monster Manual IV", "page": "44" },
  { "name": "Elf, Drow Priestess", "CR": "7", "book": "Monster Manual IV", "page": "45" },
  { "name": "Elf, Drow Spellsword", "CR": "5", "book": "Monster Manual IV", "page": "46" },
  { "name": "Fell Taint", "CR": "6", "book": "Monster Manual IV", "page": "48" },
  { "name": "Flesh Jelly", "CR": "6", "book": "Monster Manual IV", "page": "50" },
  { "name": "Forest Troll", "CR": "6", "book": "Monster Manual IV", "page": "52" },
  { "name": "Ghost Brute", "CR": "7", "book": "Monster Manual IV", "page": "54" },
  { "name": "Gibbering Orb", "CR": "12", "book": "Monster Manual IV", "page": "56" },
  { "name": "Gloom", "CR": "10", "book": "Monster Manual IV", "page": "58" },
  { "name": "Greenvise", "CR": "6", "book": "Monster Manual IV", "page": "60" },
  { "name": "Grisgol", "CR": "12", "book": "Monster Manual IV", "page": "62" },
  { "name": "Hobgoblin Bladebearer", "CR": "3", "book": "Monster Manual IV", "page": "64" },
  { "name": "Hobgoblin Warsoul", "CR": "6", "book": "Monster Manual IV", "page": "66" },
  { "name": "Inferno Spider", "CR": "8", "book": "Monster Manual IV", "page": "68" },
  { "name": "Karsite", "CR": "4", "book": "Monster Manual IV", "page": "70" },
  { "name": "Krenshar Pack Lord", "CR": "4", "book": "Monster Manual IV", "page": "72" },
  { "name": "Kythons (Adult, Broodling, Slaymaster)", "CR": "4–10", "book": "Monster Manual IV", "page": "74" },
  { "name": "Lamia Matriarch", "CR": "8", "book": "Monster Manual IV", "page": "78" },
  { "name": "Magma Hurler", "CR": "5", "book": "Monster Manual IV", "page": "80" },
  { "name": "Mongrelfolk", "CR": "1", "book": "Monster Manual IV", "page": "82" },
  { "name": "Mummy, Desert", "CR": "6", "book": "Monster Manual IV", "page": "84" },
  { "name": "Necromental", "CR": "9", "book": "Monster Manual IV", "page": "86" },
  { "name": "Nightmare Beast", "CR": "17", "book": "Monster Manual IV", "page": "88" },
  { "name": "Phthisic", "CR": "6", "book": "Monster Manual IV", "page": "90" },
  { "name": "Rage Drake", "CR": "7", "book": "Monster Manual IV", "page": "92" },
  { "name": "Ravager", "CR": "20", "book": "Monster Manual IV", "page": "94" },
  { "name": "Razormouth Swarm", "CR": "3", "book": "Monster Manual IV", "page": "96" },
  { "name": "Rejkar", "CR": "5", "book": "Monster Manual IV", "page": "98" },
  { "name": "Sea Drake", "CR": "12", "book": "Monster Manual IV", "page": "100" },
  { "name": "Shadow Spider", "CR": "6", "book": "Monster Manual IV", "page": "102" },
  { "name": "Shambling Mound, Elder", "CR": "11", "book": "Monster Manual IV", "page": "104" },
  { "name": "Skeletal Reaper", "CR": "9", "book": "Monster Manual IV", "page": "106" },
  { "name": "Skull Lord", "CR": "10", "book": "Monster Manual IV", "page": "108" },
  { "name": "Spiderstone Golem", "CR": "10", "book": "Monster Manual IV", "page": "110" },
  { "name": "Sporebat", "CR": "1", "book": "Monster Manual IV", "page": "112" },
  { "name": "Stonewalker", "CR": "7", "book": "Monster Manual IV", "page": "114" },
  { "name": "Tempest", "CR": "13", "book": "Monster Manual IV", "page": "116" },
  { "name": "Troll, Fell", "CR": "7", "book": "Monster Manual IV", "page": "118" },
  { "name": "Troll, Forest", "CR": "6", "book": "Monster Manual IV", "page": "120" },
  { "name": "Troll Slasher", "CR": "8", "book": "Monster Manual IV", "page": "122" },
  { "name": "Trollhunter Troll", "CR": "9", "book": "Monster Manual IV", "page": "124" },
  { "name": "Undead Behemoth", "CR": "12", "book": "Monster Manual IV", "page": "126" },
  { "name": "Vampire Lord", "CR": "12", "book": "Monster Manual IV", "page": "128" },
  { "name": "Vampiric Ixitxachitl", "CR": "3", "book": "Monster Manual IV", "page": "130" },
  { "name": "War Troll", "CR": "10", "book": "Monster Manual IV", "page": "132" },
  { "name": "Wight Commander", "CR": "6", "book": "Monster Manual IV", "page": "134" },
  { "name": "Zombie Hulk", "CR": "4", "book": "Monster Manual IV", "page": "136" }
]
///Monster Manual IV above


//Monster Generator
const generateMonsterButton = document.getElementById("generateMonsterButton");
const crSelect = document.getElementById("crSelect");

generateMonsterButton.addEventListener("click", () => {
  const selectedCR = crSelect.value;
  const filtered = monsters.filter(c => c.CR === selectedCR);

  if (filtered.length === 0) {
    generateMonsterButton.textContent = `No creatures found for CR ${selectedCR}`;
    return;
  }

  const randomCreature = filtered[Math.floor(Math.random() * filtered.length)];
  generateMonsterButton.textContent = `${randomCreature.name} - ${randomCreature.book} - page ${randomCreature.page}`;
});








//roller: 
const imageListRoller = [
  'images/roller_images/1.png', 'images/roller_images/2.png', 'images/roller_images/3.png', 'images/roller_images/4.png', 'images/roller_images/5.png', 'images/roller_images/6.png',
  'images/roller_images/7.png', 'images/roller_images/8.png', 'images/roller_images/9.png', 'images/roller_images/10.png', 'images/roller_images/11.png', 'images/roller_images/12.png',
  'images/roller_images/13.png', 'images/roller_images/14.png', 'images/roller_images/15.png', 'images/roller_images/16.png', 'images/roller_images/17.png', 'images/roller_images/18.png',
  'images/roller_images/19.png', 'images/roller_images/20.png'];


function showRandomImage() {
  const randomIndex = Math.floor(Math.random() * 20); // number 0–19
  const selectedImage = imageListRoller[randomIndex];
  const imageBoxRoller = document.getElementById('imageBoxRoller');
  imageBoxRoller.innerHTML = `<img src="${selectedImage}" alt="Random Image">`;
}
document.getElementById('imageBoxRoller').addEventListener('click', showRandomImage);



//map generator:
document.getElementById("generateMap").addEventListener("click", () => {
  const biome = document.getElementById("biomeSelect").value;
  const biomeObject = {
    'badlands': ['images/map_images/badlands/1.jpg', 'images/map_images/badlands/2.jpg', 'images/map_images/badlands/3.jpg', 'images/map_images/badlands/4.jpg', 'images/map_images/badlands/5.jpg', 'images/map_images/badlands/6.jpg', 'images/map_images/badlands/7.jpg', 'images/map_images/badlands/8.jpg', 'images/map_images/badlands/9.jpg', 'images/map_images/badlands/10.jpg', 'images/map_images/badlands/11.jpg', 'images/map_images/badlands/12.jpg', 'images/map_images/badlands/13.jpg', 'images/map_images/badlands/14.jpg', 'images/map_images/badlands/15.jpg', 'images/map_images/badlands/16.jpg'],
    'caves' : ['images/map_images/caves/1.jpg', 'images/map_images/caves/2.jpg', 'images/map_images/caves/3.jpg', 'images/map_images/caves/4.jpg', 'images/map_images/caves/5.jpg', 'images/map_images/caves/6.jpg', 'images/map_images/caves/7.jpg', 'images/map_images/caves/8.jpg', 'images/map_images/caves/9.jpg', 'images/map_images/caves/10.jpg', 'images/map_images/caves/11.jpg', 'images/map_images/caves/12.jpg', 'images/map_images/caves/13.jpg', 'images/map_images/caves/14.jpg', 'images/map_images/caves/15.jpg', 'images/map_images/caves/16.jpg'],
    'desert': ['images/map_images/desert/1.jpg', 'images/map_images/desert/2.jpg', 'images/map_images/desert/3.jpg', 'images/map_images/desert/4.jpg', 'images/map_images/desert/5.jpg', 'images/map_images/desert/6.jpg', 'images/map_images/desert/7.jpg', 'images/map_images/desert/8.jpg', 'images/map_images/desert/9.jpg', 'images/map_images/desert/10.jpg', 'images/map_images/desert/11.jpg', 'images/map_images/desert/12.jpg',],
    'forest': ['images/map_images/forest/1.jpg', 'images/map_images/forest/2.jpg', 'images/map_images/forest/3.jpg', 'images/map_images/forest/4.jpg', 'images/map_images/forest/5.jpg', 'images/map_images/forest/6.jpg', 'images/map_images/forest/7.jpg', 'images/map_images/forest/8.jpg', 'images/map_images/forest/9.jpg', 'images/map_images/forest/10.jpg', 'images/map_images/forest/11.jpg', 'images/map_images/forest/12.jpg', 'images/map_images/forest/13.jpg', 'images/map_images/forest/14.jpg', 'images/map_images/forest/15.jpg', 'images/map_images/forest/16.jpg'],
    'grassland': ['images/map_images/grassland/1.jpg', 'images/map_images/grassland/2.jpg', 'images/map_images/grassland/3.jpg', 'images/map_images/grassland/4.jpg', 'images/map_images/grassland/5.jpg', 'images/map_images/grassland/6.jpg', 'images/map_images/grassland/7.jpg', 'images/map_images/grassland/8.jpg', 'images/map_images/grassland/9.jpg', 'images/map_images/grassland/10.jpg', 'images/map_images/grassland/11.jpg', 'images/map_images/grassland/12.jpg', 'images/map_images/grassland/13.jpg', 'images/map_images/grassland/14.jpg', 'images/map_images/grassland/15.jpg', 'images/map_images/grassland/16.jpg'],
    'jungle': ['images/map_images/jungle/1.jpg', 'images/map_images/jungle/2.jpg', 'images/map_images/jungle/3.jpg', 'images/map_images/jungle/4.jpg', 'images/map_images/jungle/5.jpg', 'images/map_images/jungle/6.jpg', 'images/map_images/jungle/7.jpg', 'images/map_images/jungle/8.jpg', 'images/map_images/jungle/9.jpg', 'images/map_images/jungle/10.jpg', 'images/map_images/jungle/11.jpg', 'images/map_images/jungle/12.jpg', 'images/map_images/jungle/13.jpg', 'images/map_images/jungle/14.jpg', 'images/map_images/jungle/15.jpg', 'images/map_images/jungle/16.jpg'],
    'snowy forest': ['images/map_images/snowy forest/1.jpg', 'images/map_images/snowy forest/2.jpg', 'images/map_images/snowy forest/3.jpg', 'images/map_images/snowy forest/4.jpg', 'images/map_images/snowy forest/5.jpg', 'images/map_images/snowy forest/6.jpg', 'images/map_images/snowy forest/7.jpg', 'images/map_images/snowy forest/8.jpg', 'images/map_images/snowy forest/9.jpg', 'images/map_images/snowy forest/10.jpg', 'images/map_images/snowy forest/11.jpg', 'images/map_images/snowy forest/12.jpg', 'images/map_images/snowy forest/13.jpg', 'images/map_images/snowy forest/14.jpg', 'images/map_images/snowy forest/15.jpg', 'images/map_images/snowy forest/16.jpg'],
    'snowy grassland': ['images/map_images/snowy grassland/1.jpg', 'images/map_images/snowy grassland/2.jpg', 'images/map_images/snowy grassland/3.jpg', 'images/map_images/snowy grassland/4.jpg', 'images/map_images/snowy grassland/5.jpg', 'images/map_images/snowy grassland/6.jpg', 'images/map_images/snowy grassland/7.jpg', 'images/map_images/snowy grassland/8.jpg', 'images/map_images/snowy grassland/9.jpg', 'images/map_images/snowy grassland/10.jpg', 'images/map_images/snowy grassland/11.jpg', 'images/map_images/snowy grassland/12.jpg', 'images/map_images/snowy grassland/13.jpg', 'images/map_images/snowy grassland/14.jpg', 'images/map_images/snowy grassland/15.jpg', 'images/map_images/snowy grassland/16.jpg'],
    'volcano': ['images/map_images/volcano/1.jpg', 'images/map_images/volcano/2.jpg', 'images/map_images/volcano/3.jpg', 'images/map_images/volcano/4.jpg', 'images/map_images/volcano/5.jpg', 'images/map_images/volcano/6.jpg', 'images/map_images/volcano/7.jpg', 'images/map_images/volcano/8.jpg', 'images/map_images/volcano/9.jpg', 'images/map_images/volcano/10.jpg', 'images/map_images/volcano/11.jpg', 'images/map_images/volcano/12.jpg', 'images/map_images/volcano/13.jpg', 'images/map_images/volcano/14.jpg', 'images/map_images/volcano/15.jpg', 'images/map_images/volcano/16.jpg']

  
  };
  const imageList = biomeObject[biome];
  const randomIndex = Math.floor(Math.random() * imageList.length);
  const chosenImage = imageList[randomIndex];
  window.open(chosenImage, "_blank");
});






  // ALert Button 
  window.onload = function () {
    const alertBox = document.getElementById("alertBox");
    alertBox.style.display = "block";
    setTimeout(() => {
      alertBox.style.display = "none";
    }, 10000);
  };